import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500"],
  subsets: ["thai"],
  variable: "--font-kanit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${kanit.className} antialiased min-h-screen bg-main`}>
        <main className="text-main-color max-w-full mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
